version: 2

run:
  timeout: 10m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - revive
  exclusions:
    rules:

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"
      - name: package-comments
        severity: warning
        disabled: false