version: "2"

# Minimal, modern golangci-lint config.
# Keep the config simple: enable a few high-value linters and
# keep revive rules for exported symbols and package comments.
run:
  timeout: 10m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - revive
# Note: keep any revive custom rules in a separate file if needed.
# For simplicity we rely on revive's defaults here; add settings later
# if you want stricter exported/package comment checks.
