/**
 * Auto Translate Script for GitHub Issues and PRs
 * gomoqt OSS multilingual support — powered by LibreTranslate
 *
 * This script automatically translates issue/PR bodies into multiple languages
 * and posts them as a comment for better global collaboration.
 *
 * Requirements:
 * - Deno 2.0+
 * - Permissions: --allow-net, --allow-env
 * - Environment variables: GITHUB_TOKEN, GITHUB_EVENT, GITHUB_REPOSITORY
 */

import { Octokit } from "octokit";

// Supported languages list
export interface Language {
  code: string;
  flag: string;
  name: string;
}

export const languages: Language[] = [
  { code: "en", flag: "🇬🇧", name: "English" },
  { code: "ja", flag: "🇯🇵", name: "Japanese" },
  { code: "zh", flag: "🇨🇳", name: "Chinese (Simplified)" },
  { code: "ko", flag: "🇰🇷", name: "Korean" },
  { code: "fr", flag: "🇫🇷", name: "French" },
  { code: "es", flag: "🇪🇸", name: "Spanish" },
  { code: "de", flag: "🇩🇪", name: "German" },
  { code: "ru", flag: "🇷🇺", name: "Russian" },
  { code: "pt", flag: "🇵🇹", name: "Portuguese" },
  { code: "ar", flag: "🇸🇦", name: "Arabic" },
];

export interface TranslationResponse {
  translatedText: string;
}

export const translate = async (text: string, target: string): Promise<string> => {
  const res = await fetch("https://libretranslate.com/translate", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      q: text,
      source: "auto",
      target,
    }),
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Translation API failed: ${res.status} ${errorText}`);
  }

  const data: TranslationResponse = await res.json();
  return data.translatedText;
};

export interface Issue {
  number: number;
  body?: string;
}

export const parseEvent = (eventJson: string): Issue | undefined => {
  const event = JSON.parse(eventJson);
  return event.issue || event.pull_request;
};

export const generateComment = async (text: string, languages: Language[]): Promise<string> => {
  let comment = "### 🌍 Translations (Automated for Global Collaboration)\n\n";

  for (const lang of languages) {
    try {
      console.log(`📝 Translating to ${lang.name} (${lang.code})...`);
      const translated = await translate(text, lang.code);
      comment +=
        `<details><summary>${lang.flag} ${lang.name}</summary>\n\n> ${translated}\n\n</details>\n\n`;
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn(`❌ Failed to translate to ${lang.code}:`, message);
      // Continue with other languages even if one fails
    }
  }

  comment +=
    "\n---\n🤖 *Auto-generated by Translation Bot (LibreTranslate) — feel free to improve these translations via PRs!*";

  return comment;
};

if (import.meta.main) {
  // Check required environment variables
  const GITHUB_TOKEN = Deno.env.get("GITHUB_TOKEN");
  if (!GITHUB_TOKEN) {
    console.error("❌ GITHUB_TOKEN is required");
    Deno.exit(1);
  }

  const GITHUB_REPOSITORY = Deno.env.get("GITHUB_REPOSITORY");
  if (!GITHUB_REPOSITORY) {
    console.error("❌ GITHUB_REPOSITORY is required");
    Deno.exit(1);
  }

  const octokit = new Octokit({ auth: GITHUB_TOKEN });

  const eventJson = Deno.env.get("GITHUB_EVENT") || "{}";
  const [owner, repoName] = GITHUB_REPOSITORY.split("/");

  const issue = parseEvent(eventJson);
  if (!issue) {
    console.log("ℹ️ No issue or pull_request found in the event.");
    Deno.exit(0);
  }

  const text = issue.body?.trim();
  if (!text) {
    console.log("ℹ️ No body text to translate.");
    Deno.exit(0);
  }

  try {
    console.log("🚀 Starting translation process...");

    const comment = await generateComment(text, languages);

    console.log("📤 Posting translation comment...");
    await octokit.request(
      "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
      {
        owner,
        repo: repoName,
        issue_number: issue.number,
        body: comment,
      },
    );

    console.log("✅ Translation comment posted successfully.");
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error("❌ Unexpected error:", message);
    Deno.exit(1);
  }
}
