mock:
	mockgen -source=../session.go -destination=./mock_session.go
	mockgen -source=../announce_stream.go -destination=./mock_announce_stream.go
	mockgen -source=../subscribe_stream.go -destination=./mock_subscribe_stream.go
	mockgen -source=../group_writer.go -destination=./mock_group_writer.go