name: "Bug Report"
description: "Report unexpected behavior or issues"
title: "[BUG] "
labels: ["type:bug", "status:triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting this bug! Please provide detailed information.

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "Describe what happened"
      placeholder: |
        Example) Calling `client.Subscribe()` causes a panic
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the bug"
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should happen"
      placeholder: "Example) Successfully connect and receive data"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened"
      placeholder: "Example) panic: nil pointer dereference"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Error logs or stack traces"
      render: text
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: "Operating System"
      placeholder: "Example) Windows 11, macOS 14, Linux (Ubuntu 22.04)"
    validations:
      required: true

  - type: input
    id: go_version
    attributes:
      label: "Go Version"
      placeholder: "Example) go version go1.21.0"
    validations:
      required: true

  - type: input
    id: project_version
    attributes:
      label: "Project Version"
      placeholder: "Example) commit hash, tag, or branch"
    validations:
      required: true

  - type: textarea
    id: code_sample
    attributes:
      label: "Minimal Reproduction Code"
      description: "Minimal code that reproduces the bug"
      render: go
      placeholder: |
        ```go
        func ExampleBug() {
          // Minimal code that reproduces the bug
        }
        ```
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I searched for existing issues"
          required: true
        - label: "I can reproduce on the main branch"
          required: true
        - label: "I have included relevant logs"
          required: false
