name: linter

on:
  pull_request:
   branches: [ "main" ]



jobs:
  
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    env:
      GO_VERSION: 1.22

  
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ GO_VERSION }}

    - name: Lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        level: warning
        reporter: github-pr-review
        go_version: ${{ GO_VERSION }}
        golangci_lint_flags: "--config=.github/.golangci.yml"