name: Moq Web Deno CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify Deno installation
        run: deno --version

      - name: Run linter
        working-directory: ./moq-web
        run: deno lint src/ test-utils/

      - name: Run formatter check
        working-directory: ./moq-web
        run: deno fmt --check

      - name: Run type check
        working-directory: ./moq-web
        run: deno check mod.ts

      - name: Run tests
        working-directory: ./moq-web
        run: deno task test

      - name: Generate coverage
        working-directory: ./moq-web
        run: |
          deno test --allow-all --coverage=cov
          deno coverage cov --lcov --output=coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./moq-web/coverage.lcov
          flags: moq-web-deno
          name: moq-web-deno-coverage
          fail_ci_if_error: false
          verbose: true
